### ISSUE TITLE
Error during `terraform apply` with ansible_playbook resource

### ISSUE THREAD

**Issue by spham** [ansible/terraform-provider-ansible#100]
Hello,

I've encountered an unexpected error with the Ansible provider for Terraform when attempting to apply a configuration that includes the `ansible_playbook` resource. The process fails with a specific error suggesting a problem within the provider plugin.

**Terraform Version:** 1.7.5

**Ansible Provider Version:** 1.2.0

**Error Message:**
```
Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.
  with ansible_playbook.web_deployment,
  on main.tf line 21, in resource "ansible_playbook" "web_deployment":
  21: resource "ansible_playbook" "web_deployment" {
```

**Steps to Reproduce:**
1. Initialize Terraform with the Ansible provider configured.
2. Execute `terraform apply` with a configuration that uses an `ansible_playbook` resource.

I can successfully run `terraform apply` locally without issues. However, the same operation fails when executed through a GitLab CI/CD pipeline, indicating a potential issue with how the Ansible provider handles execution within GitLab's environment.

**GitLab CI Configuration:**

```yaml
stages:
  - validate
  - plan
  - apply
  - destroy

default:
  image:
    name: hashicorp/terraform:1.7.5
    entrypoint:
      - "/bin/sh"
      - "-c"

variables:
  TF_ROOT: ${CI_PROJECT_DIR}/terraform
  STATE_NAME: ${CI_COMMIT_REF_NAME}
  TF_STATE_NAME: default
  TF_ADDRESS: "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${STATE_NAME}"

.terraform_init: &terraform_init
  - >
    terraform -chdir=${TF_ROOT} init -upgrade -reconfigure
    -backend-config="address=${TF_ADDRESS}"
    -backend-config="lock_address=${TF_ADDRESS}/lock"
    -backend-config="unlock_address=${TF_ADDRESS}/lock"
    -backend-config="username=${TF_USERNAME}"
    -backend-config="password=${GITLAB_ACCESS_TOKEN}"
    -backend-config="lock_method=POST"
    -backend-config="unlock_method=DELETE"
    -backend-config="retry_wait_min=5"

before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - "which ssh-agent || ( apk update && apk add --no-cache openssh )"
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - *terraform_init

validate:
  stage: validate
  script:
    - terraform -chdir=${TF_ROOT} validate

plan:
  stage: plan
  script:
    - terraform -chdir=${TF_ROOT} plan -out=${CI_PROJECT_DIR}/tfplan
  artifacts: { paths: ["${CI_PROJECT_DIR}/tfplan"] }

apply:
  stage: apply
  script:
    - export TF_LOG="DEBUG"
    - terraform -chdir=${TF_ROOT} apply -auto-approve ${CI_PROJECT_DIR}/tfplan
  when: manual

destroy:
  stage: destroy
  script:
    - terraform -chdir=${TF_ROOT} destroy -auto-approve
  when: manual
```

**Terraform Configuration:**

```hcl
esource "hcloud_server" "web" {
  name        = "devops-web"
  server_type = "cx21"
  image       = "ubuntu-22.04"
  ssh_keys    = ["jonhdo@pham-desk"]
}

resource "ansible_host" "web_server" {
  name   = "hetzner"
  groups = ["all"]
  variables = {
    ansible_host                 = hcloud_server.web.ipv4_address
    ansible_user                 = "root"
    ansible_ssh_private_key_file = "~/.ssh/id_rsa"
    ansible_port                 = 22
    ansible_ssh_common_args      = "-o StrictHostKeyChecking=no"
    ansible_ssh_extra_args       = "-vvvv"
  }
}

resource "ansible_playbook" "web_deployment" {
  name       = hcloud_server.web.ipv4_address
  playbook   = "../ansible/playbook.yml"
  depends_on = [hcloud_server.web]
  extra_vars = {
    ansible_user = "root"
  }
}
```

This discrepancy suggests environmental differences or nuances in the Ansible provider's interaction with GitLab CI's execution environment.

**Project Structure:**
```
.
├── ansible
│   └── playbook.yml
├── hosts.yaml
├── README.md
└── terraform
    ├── ansible.cfg
    ├── backend.tf
    ├── main.tf
    ├── outputs.tf
    ├── providers.tf
    └── variables.tf
```

Any insights or guidance on addressing this discrepancy would be greatly appreciated.
