### ISSUE TITLE
Support more complex variables types

### ISSUE THREAD

**Issue by raspbeguy** [ansible/terraform-provider-ansible#128]
Hello,

When using a `ansible_host` or `ansible_group` resource, I wish I could set variables with complex types instead of only strings.

For instances I would like to set a list or a map (those types are supported in static yaml variables files in Ansible). For example I wish I could have this:

```hcl
resource "ansible_host" "starship" {
  name = "destroyer"
  variables = {
    components = [ "engine", "weapons" ]
  }
]
```

which would be equivalent to this static Ansible config:

```yaml
---
components:
  - engine
  - weapons
```

**Comment by sikha-root** [comment]
For a workaround, JSON encoding and decoding should work for several use cases, but requires setting two variables.

```hcl
resource "ansible_host" "example" {
  name   = "example"
  variables = {
    peers_json = jsonencode({
      "host01" = {
        abc = "xyz"
      }
    })
  }
}
```

```yaml
---
- name: some play
  hosts: example
  roles:
    - hjkl.hjkl
  vars:
    peers: "{{ peers_json | from_json }}"
```
