### ISSUE TITLE
ansible_playbook supports multiple hosts

### ISSUE THREAD

**Issue by LZiHaN** [ansible/terraform-provider-ansible#56]
The name parameter of the ansible_playbook resource supports multiple hosts.
eg
`
resource "ansible_playbook" "playbook" {
  playbook   = "playbook.yml"
  name       = "host-1.example.com,host-2.example.com,host-3.example.com"
  replayable = true

  extra_vars = {
    var_a = "Some variable"
    var_b = "Another variable"
  }
}
`

**Comment by pavanyejare** [comment]
Any update on this

**Comment by frostyfab** [comment]
This is a duplicate of #19 and/or related...

I would suggest to go a step further with the implementation and allow for arrays to be passed to `name` too. Passing names comma separated (no spaces) is a implementation detail that should get hidden from user IMHO. Especially since name gets `split` again in code anyways.

Consider the following use case:
```

locals {
  all_cluster_hosts        = concat(module.kube-control.vm_name, module.kube-worker.vm_name)
  all_cluster_hosts_string = join(",", [for host in local.all_cluster_hosts : "${host}.local"])
}

resource "ansible_playbook" "kube_cluster_join" {
  name     = local.all_cluster_hosts_string
}
```

<img src="https://github.com/ansible/terraform-provider-ansible/assets/140175283/c87ba4c2-f128-4886-957a-dad2a500ab44" width="50%">

**Comment by geekscrapy** [comment]
It would also help if you could enumerate hosts defined in `ansible_hosts` resources (I haven't found a way to do this yet?)

**Comment by tincore** [comment]
Not sure if anybody commented this but separating hosts using line breaks seems to work. 

CDKTF sample (Typescript)
```
    const host1 = new Host(this, 'host1', {
      name: 'host1.domain.com',
      groups: [serverGroup.name],
      variables: {
        ansible_user: 'x1',
        ansible_ssh_private_key: '~/.ssh/id_rsa',
        ansible_python_interpreter: '/usr/bin/python3'
      }
   })

   [...]
    const host2 = new Host(this, 'host2', {
   [...]
    const host3 = new Host(this, 'host3', {
   [...]

    const playbook = new Playbook(this, 'playbook', {
      playbook:  'playbooks/sample.playbook.yaml',
      name: [host1, host2, host3].maline breaksp((h) => h.name).join('\n'),
      groups: [networkGroup, serverGroup].map((g) => g.name), 

``` 

Some inconveniences with this workaround are:
- Host declared Groups are not taken into consideration when rendering the inventory (that could be nice).
- Host variables are ignored and those can be very important. I can create the files myself as a hack but then they need to be removed after execution. 
- Also there is *afaik* no way to influence the location of the temporary inventory.
```
    new File(this, 'host1Vars', {
      content: Fn.yamlencode(host1.variables),
      filename: `/tmp/host_vars/${host1.name}.yaml`
    })
```

**Comment by ShanePresley** [comment]
Why is `name` even a thing here? Ansible playbooks run over an inventory. I am using terraform to provision VMs for kubespray. I want to use this provider to build an inventory then run kubespray across that inventory. Outside of this provider this is one invocation of one playbook pointed at one inventory with [g] groups with [n] nodes... this does not seem like an uncommon use case. Why is this "ansible_playbook" resource limited to running on explicit hosts?

**Comment by ShanePresley** [comment]
I'll try to put a finer point on what I am suggesting...I thought I would be able to use this provider to arrive at the inventory below:
```
kubespray-cn1 ansible_host=192.168.1.100 etcd_member_name=etcd1
kubespray-wn1 ansible_host=192.168.1.200

[kube_control_plane]
kubespray-cn1
[kube_control_plane:vars]
group_var_value=control

[kube_node]
kubespray-wn1
[kube_node:vars]
group_var_value=node

[etcd:children]
kube_control_plane
```
do some vault stuff, extending the example a bit: 
```
---
# ++++++++++++++
# Create an empty text file on a host
# ++++++++++++++
- hosts: all
  vars:
    simple_file: ~/simple-file.{{ ansible_host }}.txt
  tags:
    - tag1
  tasks:
    - ansible.builtin.file:
        path: "{{ simple_file }}"
        state: touch

# ++++++++++++++
# Write into a text file on a host
# ++++++++++++++
- hosts: kube_control_plane
  vars:
    simple_file: ~/simple-file.{{ ansible_host }}.txt
  tags:
    - tag2
  tasks:
    - ansible.builtin.copy:
        content: |
          Hello from {{ ansible_host }}
          host_var_value: {{ etcd_member_name | default('not set') }}
          group_var_value: {{ group_var_value }}
          vaulted value: {{ vaulted_value }}
        dest: "{{ simple_file }}"

# ++++++++++++++
# Write into a text file on a host
# ++++++++++++++
- hosts: kube_node
  vars:
    simple_file: ~/simple-file.{{ ansible_host }}.txt
  tags:
    - tag2
  tasks:
    - ansible.builtin.copy:
        content: |
          Hello from {{ ansible_host }}
          host_var_value: {{ etcd_member_name | default('not set') }}
          group_var_value: {{ group_var_value }}
          vaulted value: {{ vaulted_value }}
        dest: "{{ simple_file }}"
```
run that with the equivalent of `$ ansible-playbook -i hosts.ini playbook.yml  --extra-vars "@vault.yml"` from terraform where of course the inventory is what I built using the provider and this would result in:
```
$ more ~/simple-file.*|cat
::::::::::::::
~/simple-file.192.168.1.100.txt
::::::::::::::
Hello from 192.168.1.100
host_var_value: etcd1
group_var_value: control
vaulted value: HELP! I AM LOCKED IN A VAULT!!!
::::::::::::::
~/simple-file.192.168.1.200.txt
::::::::::::::
Hello from 192.168.1.200
host_var_value: not set
group_var_value: node
vaulted value: HELP! I AM LOCKED IN A VAULT!!!
```
I don't think that is possible as the provider is implemented. Am I wrong? Is this unreasonable?
