### ISSUE TITLE
Support for Terragrunt

### ISSUE THREAD

**Issue by EdanBrooke** [ansible/terraform-provider-ansible#95]
Hi,

I would like to use this plugin to dynamically build our Ansible inventories. I got this working with Terraform on its own, but we're now looking to use Terragrunt with HTTP (GitLab) remote state. This doesn't seem to be possible at the moment as specifying the path to the a Terragrunt directory doesn't yield a backend configuration or a Terraform state file:

```
.
├── common
│   └── azurerm
│       └── core.hcl
├── lab
│   ├── azurerm
│   │   └── core
│   │       └── terragrunt.hcl
│   └── env.hcl
└── tst
    └── env.hcl
```

```
---
plugin: cloud.terraform.terraform_provider
state_file: "" # Use remote Terraform state by specifying empty string, issue #52 
project_path: ../../lab/azurerm/core
search_child_modules: True
```

Is there a particular place I should post in the community to discuss this?

**Comment by EdanBrooke** [comment]
Hello,

The below works, specifying the Terraform binary as Terragrunt.

```yaml
---
plugin: cloud.terraform.terraform_provider
binary_path: "/home/linuxbrew/.linuxbrew/bin/terragrunt" # Use Terragrunt wrapper
project_path: "../terraform/environments/lab/azurerm/core"
search_child_modules: True
```

Of course, for this to work you'd have to create a separate YAML file inside your `inventory` directory for each Terragrunt directory that yields Ansible Terraform provider resources. I'm OK with this personally.

However, specifying only `terragrunt` fails. I believe that adding support for `binary_path` to be either absolute, or relative to any path within `$PATH` may be an effective way to resolve this?

Thanks.
